@DJANGO/hackathon/cameraapp/urls.py
from django.urls import path

from cameraapp.views import live, home, off

app_name = 'cameraapp'

urlpatterns = [
    path('', home, name='home'),
    path('live/', live, name='camera'),
    # path('on/', on, name='on'),
    path('off/', off, name='off')
]

@DJANGO/hackathon/hackathon/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from videoapp.views import hello_helmet



urlpatterns = [
    path('', hello_helmet, name='home'),
    path('admin/', admin.site.urls),
    path('videos/', include('videoapp.urls')),
    path('camera/', include('cameraapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

@DJANGO/hackathon/videoapp/urls.py
from django.urls import path

from videoapp.views import VideoListView, VideoCreateView, VideoDetailView, hello_helmet

app_name = 'videoapp'

urlpatterns = [
    path('', hello_helmet, name='home'),
    path('list/', VideoListView.as_view(), name='list'),
    path('create/', VideoCreateView.as_view(), name='create'),
    path('detail/<int:pk>', VideoDetailView.as_view(), name='detail'),
]

@DJANGO/hackathon/cameraapp/models.py
from django.db import models

# Create your models here.

@DJANGO/hackathon/videoapp/models.py
from django.db import models

# Create your models here.


class Video(models.Model):
    title = models.CharField(max_length=200)
    video_file = models.FileField(upload_to='videos/', null=True)
    upload_time = models.DateTimeField(auto_now_add=True)
    yolo_file = models.FileField(upload_to='yolovideos/',null=True)

@DJANGO/hackathon/videoapp/forms.py
from django import forms
from django.forms import ModelForm

from videoapp.models import Video


class VideoCreationForm(ModelForm):

    class Meta:
        model = Video
        fields = ['title', 'video_file']

@DJANGO/hackathon/cameraapp/views.py
from django.shortcuts import render

# Create your views here.
from django.views.decorators import gzip
from django.http import StreamingHttpResponse
import cv2
import main
import threading
from django.http import JsonResponse

# https://blog.miguelgrinberg.com/post/video-streaming-with-flask/page/8
cam = None


def home(request):
    context = {}
    return render(request, "cameraapp/camera-off.html", context)


class VideoCamera(object):
    def __init__(self):
        self.video = cv2.VideoCapture(0)
        (self.grabbed, self.frame) = self.video.read()
        threading.Thread(target=self.update, args=()).start()

    def __del__(self):
        self.video.release()

    def update(self):
        while True:
            (self.grabbed, self.frame) = self.video.read()


def gen(camera):
    model = main.MyYolo.GET()
    while True:
        frame = model.process_cam(camera)
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')


@gzip.gzip_page
def live(request):
    global cam
    try:
        cam = VideoCamera()
        return StreamingHttpResponse(gen(cam), content_type="multipart/x-mixed-replace;boundary=frame")
    except:  # This is bad! replace it with proper handling
        print("에러입니다...")


def off(request):
    global cam
    if cam != None:
        cam.video.release()
        cv2.destroyAllWindows()
        cam = None
    return JsonResponse({'state': True})

@DJANGO/hackathon/videoapp/views.py
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, DetailView
from django.views.generic.edit import FormMixin

from videoapp.forms import VideoCreationForm
from videoapp.models import Video
import main


def hello_helmet(request):
    return render(request, 'videoapp/home.html')



class VideoCreateView(CreateView):
    model = Video
    form_class = VideoCreationForm
    #success_url = reverse_lazy('videoapp:list')  # create 가 성공적으로 수행이 되면 yolo 에 detail view 로 연결
    template_name = 'videoapp/create.html'

    def get_success_url(self):
        v = self.model.objects.get(pk=self.object.pk)
        videofile = v.video_file
        yolo = main.MyYolo.GET()
        yolo.processVideo('media/'+str(videofile),'media/yolovideos'+str(videofile)[6:])
        v.yolo_file = 'yolovideos'+str(videofile)[6:]
        v.save()
        return reverse('videoapp:detail', kwargs={'pk': self.object.pk})


class VideoDetailView(DetailView):
    model = Video
    context_object_name = 'target_video'
    template_name = 'videoapp/detail.html'


    # button 을 누르면 yolomodel 과정 통과







class VideoListView(ListView):
    model = Video
    context_object_name = 'video_list'
    template_name = 'videoapp/list.html'
    paginate_by = 10

@DJANGO/hackathon/cameraapp/templates/cameraapp/camera-off.html
{% extends 'base.html' %}

{% block content %}
    <div class="camera">
        <h1>실시간 분석</h1>
        <div class="camera-control">
            <button id="live-on" class="btn btn-success">시작</button>
            <button id="live-off" class="btn btn-danger">정지</button>
        </div>
    </div>
    <div class="live-image"></div>

    <script>
        let flag = false;
            window.addEventListener('click',(e)=>{
            if(e.target.id == 'live-on' && !flag){
                const imgTag = document.createElement('img')
                imgTag.id = 'live'
                imgTag.src = "http://127.0.0.1:8000/camera/live"
                const parentDiv = document.querySelector('.live-image');
                parentDiv.appendChild(imgTag)
                flag = true;
            } else if (flag && e.target.id == 'live-off'){
                axios.get('/camera/off/')
                .then((response)=>{
                    console.log(response);
                    const imgTag = document.querySelector('#live');
                    imgTag.remove();
                    setTimeout(function(){
                      flag = false
                    },5000)
                })
            }
        })
        window.addEventListener('beforeunload',(e)=>{
            if(flag){
                axios.get('/camera/off/').then((res) => {
                    console.log(res)
                })
            }
        })
    </script>
{% endblock %}

@DJANGO/hackathon/cameraapp/templates/cameraapp/camera-on.html
{% extends 'base.html' %}

{% block content %}
    <h1>실시간 분석</h1>
    <div>
        <span class="btn btn-success">
            <a href="{% url 'cameraapp:on' %}">시작</a>
        </span>
        <span class="btn btn-danger">
            <a href="{% url 'cameraapp:off' %}">정지</a>
        </span>
    </div>
    <div>
        <img src="http://127.0.0.1:8000/camera/live" style="width:500px;"/>
    </div>
{% endblock %}

@DJANGO/hackathon/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% include 'head.html' %}
<body>
{% include 'header.html' %}
<hr>

{% include 'sidebar.html' %}
<div class="content">
    {% block content %}
    {% endblock %}
</div>

<hr>

{% include 'footer.html' %}
</body>
</html>

@DJANGO/hackathon/templates/footer.html
<div class="footer">
    <div>
        <span class="btn"><i class="fab fa-twitter"></i></span>
        <span class="btn"><i class="fab fa-instagram"></i></span>
        <span class="btn"><i class="fab fa-facebook-square"></i></span>
        <p> Copyright 광주 인공지능 사관학교 (강병국, 신하섬, 이정무, 천영성)</p>
    </div>
</div>

@DJANGO/hackathon/templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport", content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Title</title>
    {#  Bootstrap Link  #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    {#  Stylesheet  #}
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    {#  Font Awesome  #}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
</head>

@DJANGO/hackathon/templates/header.html
<div class="header">
    <h1>Save Your Life</h1>
</div>

@DJANGO/hackathon/templates/sidebar.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'toggle_sidebar.css' %}">
<body id="body-pd">
    <div class="l-navbar" id="navbar">
        <nav class="nav">
            <div>
                <div class="nav__brand">
                    <ion-icon name="menu-outline" class="nav__toggle" id="nav-toggle"></ion-icon>
                    <a href="{% url 'videoapp:home' %}" class="nav__logo">Helmetfilx</a>
                </div>
                <div class="nav__list">
                    <a href="{% url 'videoapp:home' %}"
                        class="nav__link{% if request.resolver_match.namespace == 'videoapp' and request.resolver_match.url_name == 'home' %} active{% endif %}">
                        <ion-icon name="home-outline" class="nav__icon"></ion-icon>
                        <span class="nav_name">Home</span>
                    </a>
                    <a href="{% url 'videoapp:list' %}"
                       class="nav__link{% if request.resolver_match.namespace == 'videoapp' and request.resolver_match.url_name == 'list'%} active{% endif %}">
                        <ion-icon name="save-outline" class="nav__icon"></ion-icon>
                        <span class="nav_name">업로드 영상 분석</span>
                    </a>

                    <a href="{% url 'cameraapp:home' %}"
                       class="nav__link{% if request.resolver_match.namespace == 'cameraapp' %} active{% endif %}">
                        <ion-icon name="eye-outline" class="nav__icon"></ion-icon>
                        <span class="nav_name">실시간 영상 분석</span>
                    </a>
{##}
{#                    <a href="#" class="nav__link">#}
{#                        <ion-icon name="settings-outline" class="nav__icon"></ion-icon>#}
{#                        <span class="nav_name">Settings</span>#}
{#                    </a>#}
{#                </div>#}
{#                <a href="#" class="nav__link">#}
{#                    <ion-icon name="log-out-outline" class="nav__icon"></ion-icon>#}
{#                    <span class="nav_name">Log out</span>#}
{#                </a>#}
            </div>
        </nav>
    </div>

    <!-- IONICONS -->
    <script src="https://unpkg.com/ionicons@5.2.3/dist/ionicons.js"></script>
    <!-- JS -->
    <script src="{% static 'js/toggle_sidebar.js' %}"></script>
</body>

@DJANGO/hackathon/videoapp/templates/videoapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

    <div>
        <div>
            <form action="{% url 'videoapp:create' %}" method="POST"
            enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="m-5">
                    <input class="btn btn-success" type="submit" value="작성하기">
                </div>
            </form>
        </div>
    </div>

{% endblock %}

@DJANGO/hackathon/videoapp/templates/videoapp/detail.html
{% extends 'base.html' %}
{% block content %}

    <div class="video">
        <h1>{{ target_video.title }}</h1>
        <div class="video-box">

            <video id="video1" width="500px" height="500px" controls autoplay>
                <source src="{{ target_video.video_file.url }}" type="video/mp4">
            </video>
        </div>

        <div class="video-box">
            <video id="video2" width="500px" height="500px" controls autoplay>
                <source src="{{ target_video.yolo_file.url }}" type="video/mp4">
            </video>
        </div>
    </div>

{% endblock %}

@DJANGO/hackathon/videoapp/templates/videoapp/home.html
{% extends 'base.html' %}
{% block content %}
<div>
    <img src="../../../static/images/helmet.png" alt="">
</div>
{% endblock %}

@DJANGO/hackathon/videoapp/templates/videoapp/list.html
{% extends 'base.html' %}
{% block content %}
    <div class="list-header">
        <span class="header-title">업로드된 영상 분석</span>
        <span class="btn btn-success">
            <a href="{% url 'videoapp:create' %}">
                <ion-icon name="cloud-upload-outline"></ion-icon>
                <span>Upload</span>
            </a>
        </span>
    </div>
    <div class="list-group">
    {% for video in video_list %}
          <a href="{% url 'videoapp:detail' pk=video.pk %}" class="list-group-item list-group-item-action">{{ video.title }}</a>
    {% endfor %}
    </div>
{% endblock %}

@DJANGO/hackathon/videoapp/templates/videoapp/main.html
{% extends 'base.html' %}

{% block content %}
    {% for video in video_list %}
        <div>
            <h1>{{ video.title }}</h1>
        </div>
    {% endfor %}
{% endblock %}